blueprint:
  name: Motion-Controlled Lighting 4.11 – Stable release with improved GUI, separate day/night scenes, and safe lux handling
  description: >
    Motion-controlled lighting with day/night, scenes, lux, sunrise/sunset,
    workday sensor, failsafe (separate day/night), fixed off-times (with weekdays),
    snapshots for day/night, and logging. Auto-off timers run only if no fixed off-time is active.
  domain: automation
  input:

    # --- Sensors & Switches ---
    
    motion_sensors:
      name: Motion Sensor(s)
      description: "One or more motion sensors that control the lighting."
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    optional_switches:
      name: Optional Manual Switch
      description: "Optional smart switches or outlets that can control the lights/devices."
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    # --- Lights & Scenes ---
    
    main_lights:
      name: Main Lights
      description: "Lights that always turn on when motion is detected (day or night)."
      default: []
      selector:
        target:
          entity:
            domain: light

    auto_off_main:
      name: Main Lights Duration (minutes)
      description: "How long the main lights should stay on after the last motion."
      default: 10
      selector:
        number:
          min: 0
          max: 1200
          step: 1
          unit_of_measurement: min
          mode: box

    scene_day:
      name: Day Scene
      description: "Scene activated during daytime (if selected)."
      default: []
      selector:
        entity:
          domain: scene
          multiple: false

    day_lights:
      name: Day Lights
      description: "Lights that only turn on during daytime."
      default: []
      selector:
        target:
          entity:
            domain: light

    auto_off_day:
      name: Day Lights Duration (minutes)
      description: "How long day lights should stay on after the last motion."
      default: 5
      selector:
        number:
          min: 0
          max: 1200
          step: 1
          unit_of_measurement: min
          mode: box

    scene_night:
      name: Night Scene
      description: "Scene activated during night-time (if selected)."
      default: []
      selector:
        entity:
          domain: scene
          multiple: false

    night_lights:
      name: Night Lights
      description: "Lights that only turn on during night-time."
      default: []
      selector:
        target:
          entity:
            domain: light

    auto_off_night:
      name: Night Lights Duration (minutes)
      description: "How long night lights should stay on after the last motion."
      default: 1
      selector:
        number:
          min: 0
          max: 1200
          step: 1
          unit_of_measurement: min
          mode: box

    # --- Lux & Sun ---
    
    lux_sensor:
      name: Lux Sensor
      description: "Sensor that measures illuminance (lux)."
      default: []
      selector:
        entity:
          domain: sensor
          device_class: illuminance

    lux_threshold:
      name: Lux Threshold
      description: "Lights will only turn on if the lux value is below this threshold."
      default: 50
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          unit_of_measurement: lx

    use_sun_times:
      name: Use Sunrise/Sunset Times
      description: "Enable to use sun times instead of fixed times."
      default: false
      selector:
        boolean: {}

    sunrise_offset:
      name: Sunrise Offset
      description: "Adjust the sunrise time earlier or later."
      default: "00:00:00"
      selector:
        time: {}

    sunset_offset:
      name: Sunset Offset
      description: "Adjust the sunset time earlier or later."
      default: "00:00:00"
      selector:
        time: {}

    # --- Fixed Off-Times ---
    
    fixed_off_time_1:
      name: Fixed Off-Time 1
      description: "Time when lights or smart switches automatically turn off."
      default: []
      selector:
        time: {}

    fixed_off_weekdays_1:
      name: Active Weekdays (Off-Time 1)
      description: "Weekdays when Fixed Off-Time 1 is active."
      default: []
      selector:
        select:
          multiple: true
          options:
            - label: Monday
              value: mon
            - label: Tuesday
              value: tue
            - label: Wednesday
              value: wed
            - label: Thursday
              value: thu
            - label: Friday
              value: fri
            - label: Saturday
              value: sat
            - label: Sunday
              value: sun

    fixed_off_time_2:
      name: Fixed Off-Time 2
      description: "Time when lights or smart switches automatically turn off."
      default: []
      selector:
        time: {}

    fixed_off_weekdays_2:
      name: Active Weekdays (Off-Time 2)
      description: "Weekdays when Fixed Off-Time 2 is active."
      default: []
      selector:
        select:
          multiple: true
          options:
            - label: Monday
              value: mon
            - label: Tuesday
              value: tue
            - label: Wednesday
              value: wed
            - label: Thursday
              value: thu
            - label: Friday
              value: fri
            - label: Saturday
              value: sat
            - label: Sunday
              value: sun

    # --- Time Settings ---
    
    day_start:
      name: Day Start
      description: "Time when daytime mode activates."
      default: "07:00:00"
      selector:
        time: {}

    day_end:
      name: Day End
      description: "Day end cannot be the same as Night start. Example: 22:00:00"
      default: "22:00:00"
      selector:
        time: {}

    active_weekdays_day:
      name: Active Weekdays (Day)
      description: "Select weekdays when daytime mode is active."
      default: []
      selector:
        select:
          multiple: true
          options:
            - label: Monday
              value: mon
            - label: Tuesday
              value: tue
            - label: Wednesday
              value: wed
            - label: Thursday
              value: thu
            - label: Friday
              value: fri
            - label: Saturday
              value: sat
            - label: Sunday
              value: sun

    night_start:
      name: Night Start
      description: "Night start cannot be the same as Day end. Example: 22:00:01"
      default: "22:00:01"
      selector:
        time: {}

    night_end:
      name: Night End
      description: "Time when night mode deactivates."
      default: "07:00:00"
      selector:
        time: {}

    active_weekdays_night:
      name: Active Weekdays (Night)
      description: "Select weekdays when night mode is active."
      default: []
      selector:
        select:
          multiple: true
          options:
            - label: Monday
              value: mon
            - label: Tuesday
              value: tue
            - label: Wednesday
              value: wed
            - label: Thursday
              value: thu
            - label: Friday
              value: fri
            - label: Saturday
              value: sat
            - label: Sunday
              value: sun

    # --- Workday & Failsafe ---
    
    workday_sensor:
      name: Workday Sensor
      description: "Sensor that indicates workdays. Used to select which fixed off-time applies."
      default: []
      selector:
        entity:
          domain: binary_sensor

    enable_failsafe:
      name: Enable Failsafe
      description: "Enable failsafe to turn off lights if auto-off did not trigger."
      default: true
      selector:
        boolean: {}

    failsafe_timer_day:
      name: Failsafe Timer Day (minutes)
      description: "Minutes before day lights are forcibly turned off if auto-off fails."
      default: 15
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: min

    failsafe_timer_night:
      name: Failsafe Timer Night (minutes)
      description: "Minutes before night lights are forcibly turned off if auto-off fails."
      default: 15
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: min

    input_text_last_scene:
      name: Input Text – Last Scene
      description: "Input Text entity to save the name of the last active scene (day or night)."
      default: []
      selector:
        entity:
          domain: input_text

# --- Triggers and mode ---

trigger:
  - platform: state
    entity_id: !input motion_sensors
  - platform: state
    entity_id: !input optional_switches
  - platform: sun
    event: sunrise
    offset: !input sunrise_offset
  - platform: sun
    event: sunset
    offset: !input sunset_offset
  - platform: time
    at: !input fixed_off_time_1
  - platform: time
    at: !input fixed_off_time_2

mode: restart

# --- Variables ---

variables:
  main_lights_var: !input main_lights
  day_lights_var: !input day_lights
  night_lights_var: !input night_lights
  scene_day_var: !input scene_day
  scene_night_var: !input scene_night
  last_scene_entity: !input input_text_last_scene
  lux_sensor_var: !input lux_sensor
  lux_threshold_var: !input lux_threshold
  use_sun_times_var: !input use_sun_times
  workday_sensor_var: !input workday_sensor
  auto_off_main_var: !input auto_off_main
  auto_off_day_var: !input auto_off_day
  auto_off_night_var: !input auto_off_night
  fixed_off_weekdays_1_var: !input fixed_off_weekdays_1
  fixed_off_weekdays_2_var: !input fixed_off_weekdays_2
  day_start_var: !input day_start
  day_end_var: !input day_end
  night_start_var: !input night_start
  night_end_var: !input night_end
  active_weekdays_day_var: !input active_weekdays_day
  active_weekdays_night_var: !input active_weekdays_night
  enable_failsafe_var: !input enable_failsafe
  failsafe_timer_day_var: !input failsafe_timer_day
  failsafe_timer_night_var: !input failsafe_timer_night

condition: []

# --- Actions ---

action:

  # --- Motion / Switch ON Day (with snapshot) ---
  
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: motion_on
              - condition: trigger
                id: switch_on
          - condition: template
            value_template: >
              {% if lux_sensor_var == [] %}
                true
              {% else %}
                {% set val = states(lux_sensor_var[0]) %}
                {% if val in ['unknown','unavailable','none','None',''] %}
                  false
                {% else %}
                  {{ val | float < lux_threshold_var }}
                {% endif %}
              {% endif %}
          - condition: template
            value_template: >
              {% if not use_sun_times_var %}
                {% set t = now().time() %}
                {% set start = strptime(day_start_var, '%H:%M:%S').time() %}
                {% set end = strptime(day_end_var, '%H:%M:%S').time() %}
                {% if start <= end %} {{ t >= start and t <= end }}
                {% else %} {{ t >= start or t <= end }} {% endif %}
              {% else %} true {% endif %}
          - condition: template
            value_template: >
              {% if workday_sensor_var == [] %} true
              {% else %} is_state(workday_sensor_var[0],'on') {% endif %}
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ main_lights_var + day_lights_var }}"
          - service: scene.turn_on
            target:
              entity_id: "{{ scene_day_var }}"
          - service: input_text.set_value
            data:
              entity_id: "{{ last_scene_entity }}"
              value: "{{ scene_day_var[0] if scene_day_var | length > 0 else 'None' }}"

  # --- Motion / Switch ON Night (with snapshot) ---
  
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% if not use_sun_times_var %}
                {% set t = now().time() %}
                {% set start = strptime(night_start_var, '%H:%M:%S').time() %}
                {% set end = strptime(night_end_var, '%H:%M:%S').time() %}
                {% if start <= end %} {{ t >= start and t <= end }}
                {% else %} {{ t >= start or t <= end }} {% endif %}
              {% else %} true {% endif %}
          - condition: template
            value_template: >
              {% if workday_sensor_var == [] %} true
              {% else %} is_state(workday_sensor_var[0],'on') {% endif %}
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ main_lights_var + night_lights_var }}"
          - service: scene.turn_on
            target:
              entity_id: "{{ scene_night_var }}"
          - service: input_text.set_value
            data:
              entity_id: "{{ last_scene_entity }}"
              value: "{{ scene_night_var[0] if scene_night_var | length > 0 else 'None' }}"

# --- Fixed Off-Times with Workday Sensor ---

  - choose:
      - conditions:
          - condition: trigger
            id: fixed_off_time_1
          - condition: template
            value_template: "{{ workday_sensor_var == [] or is_state(workday_sensor_var[0], 'on') }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ main_lights_var + day_lights_var + night_lights_var }}"
          - service: logbook.log
            data:
              name: Motion Lighting
              message: "Fixed Off-Time 1 executed."

      - conditions:
          - condition: trigger
            id: fixed_off_time_2
          - condition: template
            value_template: "{{ workday_sensor_var != [] and not is_state(workday_sensor_var[0], 'on') }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ main_lights_var + day_lights_var + night_lights_var }}"
          - service: logbook.log
            data:
              name: Motion Lighting
              message: "Fixed Off-Time 2 executed."

# --- Failsafe Day/Night ---

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ enable_failsafe_var }}"
        sequence:
          - variables:
              failsafe_types:
                - { name: "day", timer: failsafe_timer_day_var, lights: day_lights_var + main_lights_var, auto_off: auto_off_day_var }
                - { name: "night", timer: failsafe_timer_night_var, lights: night_lights_var + main_lights_var, auto_off: auto_off_night_var }
          - repeat:
              count: "{{ failsafe_types | length }}"
              sequence:
                - variables:
                    fs: "{{ failsafe_types[repeat.index - 1] }}"
                - delay:
                    minutes: "{{ fs.timer }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: >
                            {% set lights_on = fs.lights | select('state','on') | list %}
                            {% if lights_on | length == 0 %}
                              false
                            {% else %}
                              {% if motion_sensors | length == 0 %}
                                true
                              {% else %}
                                {% set all_off = motion_sensors | map('states') | select('equalto','off') | list | length == motion_sensors | length %}
                                {{ all_off }}
                              {% endif %}
                            {% endif %}
                      sequence:
                        - service: light.turn_off
                          target:
                            entity_id: "{{ fs.lights }}"
                        - service: logbook.log
                          data:
                            name: Motion Lighting
                            message: >
                              Failsafe {{ fs.name }}: Lights turned off after {{ fs.timer }} min, all sensors off and auto-off timers elapsed.
